---
title: "explore"
author: "Yuan Yuan"

SW: did you test your code? it doesn't work as written. i've modified it to get it working. your output is hard to read, you're dropping labels from the frequency tables, so it's difficult to tell which variable is which. and, you need to consider the absolute value of the correlation coefficient; currently, you are looking only at positive values.

```{r}
require(grid)
require(ggplot2)
explore <- function(dataframe,bin_sizes,threshold){ #Define a function named explore with  input parameters: dataframe, bin_sizes, and threshold. Bin_sizes is the vector of sizes for the histograms. Threshold is the upper limit for the correlation coefficients. 

  varnum <- dataframe[which(lapply(dataframe, is.numeric) == TRUE)] #Define a function varnum which extract all of the numeric columns from dataframe

  varfactor <- dataframe[which(lapply(dataframe, is.factor) == TRUE)] #initial a data frame which contains all of the factor columns from dataframe

  varlog <- dataframe[which(lapply(dataframe,is.logical)==TRUE)] #Define a function varlog which extract all of the factor columns from dataframe

#question 1
if (length(varnum) > 0){ #if there are numeric columns
  for (i in 1:length(varnum)){ #for loop, go through each column in the data frame
    for (bins in 1:length(bin_sizes)){ #for loop, through each bin size in the vector
      num_bins <- (max(varnum[[i]])-min(varnum[[i]]))/bin_sizes[bins] #the number of bins based on the bin size from bin_sizes
      col_mean <- mean(varnum[[i]]) #the mean of the ith numeric column
      Num_Plot <- ggplot(varnum, aes(x=varnum[[i]]), environment=environment()) #sets varnum to be the data frame for ggplot and sets the ith column to be the x aesthetic and uses the environment parameter to work on the scoping issue.
      #Num_Plot <- Num_Plot + geom_histogram(colour='blue', fill='blue', binwidth=numbins) + labs(x=names(varnum)[[i]]) + geom_vline(xintercept=col_mean, colour='red') 
      # SW: you refer to numbins, but you define an object called num_bins. you
      # would have caught this had you tested your code.
      Num_Plot <- Num_Plot + geom_histogram(colour='blue', fill='blue', binwidth=num_bins) + labs(x=names(varnum)[[i]]) + geom_vline(xintercept=col_mean, colour='red') 
      #define the histogram. The color of the bars is made to be blue and the binwidth is made to num_bins. The label for the x axis is made to be the name of the ith numeric column. A red vertical line for the mean is added.
      print(Num_Plot) #print the histogram
      print(Num_Plot + aes(y=..density..) + labs(y="Density")) #define y aesthetic to be density and define the label of the y axis to be Density. The histogram using density is printed for each numeric column
      }
    }
  }
#question 2
if (length(varfactor) > 0){ #if there are factor columns
for (i in 1:length(varfactor)){ #for loop, throught each factor column in the data frame
  bargraph <- ggplot(varfactor,aes(x=varfactor[[i]]), environment=environment()) #draw graph about varfactor and define the ith column to be the x aesthetic and uses the environment parameter to work on the scoping issue.
  bargraph <- bargraph + geom_bar(colour="gray",fill="gray") #draw the bar graph and define the color as gray
  bargraph <- bargraph + labs(x = names(varfactor)[[i]]) #define the label of the x axis to be the name of the ith column
  print(bargraph) #print the bargraph for each factor column
}
}

if (length(varlog) > 0){ #if there are binary columns
for (i in 1:length(varlog)){ #for loop, through each binary column in the data frame
  bargraph <- ggplot(varlog, aes(x=varlog[[i]]), environment=environment()) #define varlog to be the data frame for ggplot and define the ith column to be the x aesthetic and uses the environment paramter to work on the scoping issue. 
  bargraph <- bargraph + geom_bar(colour="gray",fill="gray") #draw the bar graph and define colour as gray
  bargraph <- bargraph + labs(x = names(varlog)[[i]]) #define the label of the x axis to be the name of the ith column
  print(bargraph) #print the bargraph for each binary column
} 
}

logorfac <- function(x){ #define a function logorfac with input, x
  y <- is.logical(x) | is.factor(x) #y is defined as a bool, is.logical(x) or is.factor(x). 
  return(y) #return the TRUE or FALSE, y's value
}

var_logorfac <- dataframe[which(lapply(dataframe, logorfac) == TRUE)] #initial a data frame var_logorfac contianing the logical or factor variables from inputdf

#question 4a
tablelist <- vector(mode = "list") #initial a list called tablelist

if (length(var_logorfac) > 0 ){ #if there are logical or factor columns
for (i in 1:length(var_logorfac)){ #for loop, through each binary or factor column in the data frame
  freq_table <- table(var_logorfac[[i]]) #intial a frequency table for the ith column and names the table freq_table
  tablelist[[i]] <- freq_table #add freq_table as the ith element of the tablelist
}
}

#question 4bi
summarylist <- vector(mode="list") #initial a list called summarylist

if (length(varnum) > 0){ #if there are numeric columns
for (i in 1:length(varnum)){ #for loop, throught each numeric column in the data frame
  summarytable <- summary(varnum[[i]]) #initial a summary statistics table for the ith columns and names the table summarytable
  summarylist[[i]] <- summarytable #add summarytable as the ith element of summarylist
}

corr_a <- cor(varnum, method="pearson") #initial a matrix of the pearson correlation coefficients

r_square <- NULL #initial a variable r_squre with value, NULL
rsq_names <- NULL #initial a variable rsq_names with value, NULL
corr_list <- NULL #initial a variable corr_list with value, NULL
corr_names <- NULL #initial a variable corr_names with value, NULL

len <- length(corr_a[1,]) #calculate the length of the first row of the corr_a matrix

#question 4bii
for (i in 1:(len-1)){ #for loop, through the first member of each pair of numeric variables, endding at the last two column
  for (j in (i+1):len){ #for loop, through the second member of each pair of numeric variables, starting at the column after i and endding at the last column. 
    pair_name <- paste(names(corr_a[,1])[[i]],names(corr_a[1,])[[j]],sep="-") #initial a string with the ith column name and the jth column name seperated by "-"" 
    rsq_names <- c(rsq_names, pair_name) #add the pair_name string as an element to the rsq_names vector

    #question 3
    r_square <- c(r_square, corr_a[i,j]^2) #add the r-square value from the ith row and jth column as an element to the r_square vector

    #question 4biii
     if (corr_a[i,j] > threshold) { #if the correlation coefficient is greater than the threshold
      corr_names <- c(corr_names, pair_name) #add the pair_name string as an element to the corr_names vector
      corr_list <- c(corr_list, corr_a[i,j]) #add the correlation coeffiecient from the ith row and jth column as an element to the corr_list vector 
      }
  }
}

rsq_df <- data.frame(cbind(rsq_names, r_square)) #initial a data frame from the rsq_names and r_squared vectors
names(rsq_df)[1] <- "Pair" #define the name of the first column in the rsq_df data frame to be "Pair"
names(rsq_df)[2] <- "R-Square Value" #define the name of the second column in the rsq_df data frame to be "R-Square Value"
corr_df <- data.frame(cbind(corr_names, corr_list)) #initial a data frame from the corr_names and corr_list vectors
names(corr_df)[1] <- "Pair" #define the name of the first column in the corr_df data frame to be "Pair"
names(corr_df)[2] <- "Correlation Coefficient" #define the name of the second column in the corr_df data frame to be "Correlation Coefficient"
question_4_list <- list("Frequency_tables"=tablelist, "Summary_tables"=summarylist, "R-square"=rsq_df, "Correlation"=corr_df) #initial a list of the tablelist, summarylist, rsq_df, and corr_df

print(question_4_list) #return the question_4_list
}

}

require(ggplot2) #load the ggplot2 package to use the diamonds data frame

#add the logical column to the diamonds data frame
rowc <- nrow(mtcars) #initial the rowc variable with the number of rows in the mtcars data frame
rowd <- nrow(diamonds) #initial the rowd variable with the number of rows in the diamonds data frame

col <- mtcars$vs #initial the col variable to be the vs column in the mrcars data frame

col1 <- length(which(col == 1)) #initial the col1 variable to be the number of rows with a 1 in the vs column
col0 <- length(which(col == 0)) #initial the col0 variable to be the number of rows with a 0 in the vs column

a <- round(rowd*col1/rowc) #multiply the number of rows in the diamonds data frame by the number of 1s in the vs column and divides by the total number of rows in the vs column and round it
b <- round(rowd*col0/rowc) #multiply the number of rows in the diamonds data frame by the number of 0s in the vs column and divides by the total number of rows in the vs column and round it. 

tfvec <- rep(c(TRUE,FALSE),times=c(a,b)) #define a logical vector called tfvec with a TRUE rows and b FALSE rows

diamonds$logical <- tfvec #add the tfvec vector as a column to the diamonds data frame, named logical.

#question 5
explore(diamonds, c(5,20,50), 0.25) #run the explore function with diamonds with the logical column as the data frame. a vector c(5,20,50), and the corrrelation threshold, 0.25.
explore(mtcars,c(5,20,50),0.25) #explore function with mstcars as the data frame, a vector c(5,20,50), and the corrrelation threshold, 0.25.

